### ISSUE TITLE
No support for --group and --filter

### ISSUE THREAD

**Issue by rvadym** [vektah/phpunit-parallel#3]
Maybe I'm missing something, but I didn't understand how to pass PHPUnit related flags

**Comment by Vektah** [comment]
They aren't currently implemented, we use `phpunit-parallel` to speed up our CI builds so specifying a directory is fine enough control for us.

I'll have a look at adding them this afternoon, it should be pretty straight forward.

**Comment by rvadym** [comment]
@Vektah Thank you, appreciate it.
